[package]
name = "invoice-generator-app"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = { version = "3.1.12", features = ["requestid", "compression"] }
tokio = { version = "1.48.0", features = ["rt-multi-thread", "macros"] }
serde = { version = "1.0", features = ["derive"]}